[package]
name = "traffic_analyser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.10.1"
pnet_datalink = "0.31.0"
dns-parser = "0.8"

[dependencies.pnet]
pnet = "0.31.0"
